# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_modular_headers!
require 'fileutils'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

def repair_grpc_private_headers
  pods_root = File.join(File.dirname(__FILE__), 'Pods')
  grpc_private_headers = File.join(pods_root, 'Headers', 'Private', 'grpc')
  grpc_core_headers = File.join(pods_root, 'Headers', 'Private', 'gRPC-Core', 'grpc')
  grpc_modulemap = File.join(pods_root, 'Target Support Files', 'gRPC-Core', 'gRPC-Core.modulemap')

  return unless File.exist?(grpc_modulemap)

  FileUtils.mkdir_p(grpc_private_headers)
  grpc_modulemap_target = File.join(grpc_private_headers, 'gRPC-Core.modulemap')
  FileUtils.rm_f(grpc_modulemap_target)
  FileUtils.cp(grpc_modulemap, grpc_modulemap_target)

  return unless Dir.exist?(grpc_core_headers)

  Dir.children(grpc_core_headers).each do |entry|
    source = File.join(grpc_core_headers, entry)
    target = File.join(grpc_private_headers, entry)
    FileUtils.rm_f(target)
    FileUtils.ln_sf(source, target)
  end
end


def strip_firebase_firestore_internal_weak_framework_flags(value)
  return nil unless value

  if value.is_a?(Array)
    stripped = []
    skip_next = false

    value.each_with_index do |entry, index|
      if skip_next
        skip_next = false
        next
      end

      if entry.to_s == '-weak_framework'
        skip_next = true if value[index + 1].to_s.delete('"') == 'FirebaseFirestoreInternal'
        stripped << entry unless skip_next
      elsif entry.to_s.include?('-weak_framework') && entry.to_s.include?('FirebaseFirestoreInternal')
        next
      else
        stripped << entry
      end
    end

    stripped
  elsif value.is_a?(String)
    value.gsub(/\s*-weak_framework\s+"?FirebaseFirestoreInternal"?/, '')
  else
    value
  end
end

def repair_firebase_firestore_internal_xcconfigs
  pods_root = File.join(File.dirname(__FILE__), 'Pods')
  Dir.glob(File.join(pods_root, 'Target Support Files', '**', '*.xcconfig')).each do |path|
    contents = File.read(path)
    repaired = strip_firebase_firestore_internal_weak_framework_flags(contents)
    File.write(path, repaired) if repaired && repaired != contents
  end
end

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      if config.name == 'Debug'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 x86_64'
      end

      flags = strip_firebase_firestore_internal_weak_framework_flags(config.build_settings['OTHER_LDFLAGS'])
      config.build_settings['OTHER_LDFLAGS'] = flags unless flags.nil?
    end
  end

  repair_grpc_private_headers
  repair_firebase_firestore_internal_xcconfigs
end

post_integrate do |_installer|
  repair_grpc_private_headers
  repair_firebase_firestore_internal_xcconfigs
end
